---

  - name: Build Docker image for application
    command: docker build -t webdizz/bootiful-app:{{ application_version }} .
    args:
      chdir: "{{ project_root }}/env/docker/application"

  - name: Remove downloaded artifact after image was built
    command: rm -rf {{ project_root }}/env/docker/application/{{ application_name }}
