language: java
jdk:
  - oraclejdk8

install:
  - sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
  - sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - sudo apt-get install python-pip lxc-docker
  - sudo pip install ansible

before_script:
  # Unpack ssh key for GCE
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/google_compute_engine
  - chmod 600 ~/.ssh/google_compute_engine

after_success:
  - ./gradlew :boos:bintrayUpload -PbintrayKey=$BINTRAY_KEY -Pversion="1.0.$TRAVIS_BUILD_NUMBER" -x publishMavenJavaPublicationToMavenLocal
  - ansible-playbook  -i env/deployment/lc.ini env/deployment/0_prepare.yml --extra-vars '{"application_version":"1.0.'$TRAVIS_BUILD_NUMBER'","project_root":"/home/travis/build/webdizz/bootiful-apps"}'

env:
  global:
    # ENV variable with Bintray API Key
    - secure: "PnbLPd2lg3eLqpBzZOT1LZYeszPIm0wcCd6pVb/tp/E1wI9vD544CCtmMo1pfE+gnybqb4mNzC+1VUFhUOTdUtqiuPO+4lebg+x/Bc8aPc8J/B7Gx5+qK/HCJrKzj9NjtArAGeXh65z4Miyg1p+OuXD9Zi/MvBi6ExGCz6c9cFA="
    # ENV variables of encrypted Private Key for GCE
    - secure: "Rzb9Ea9nKta1aynfMwL2PCM06j6WapjtXAX8Z+WDpQM6KLFDjB2ThJ3ifg2i0AAozwjm69AzjzDZsoYGhEFHz1emv27i+UFyPrubz6oXq6/NiXhzydycAW9PN5R9JFITMBGZ4b+vVDzP3RwHaBvU/H3FL72k4YgVfNaLL9rb+3Q="
    - secure: "dSkbbtwMKWOsVouXsNpzxbFql8Cx83kYa9Vla5q/gwmZkjygUlmQeHw9dIW6rHetA7gIHI2DA3CnpGXmbjO+hp6Qh36Ac8JlAxY639JTBZldIJZJ+z8l+i738AjQqo4UhEsIcrSH92kuSegusDsqR9ZuWH4+0YwA59UltE77sy0="
    - secure: "M9ex/ENdW8Esd5evNgTLMSIbOeEHbnur/59crMZv2vsTohxKut3JXLyomEgBbmDG1LmLTJRWbNiNLZnP7csYHHtv9Sq5S/jEaqjBpS46K/kQCfr8KGi8sfKs3hEwMV/cPdD1IM9i56hWmiyJNeX8jussbVWoAEUEjfJubBbe0aY="
    - secure: "CzkGXa4hIroGnrwCWOsp97Z1SrJFOozZY+1aQNC7IGZTFaGljr8cv97hexYxfi/Mo5NXe2IGoE6dsO+HVDvyg2sGPnRXCqAAE7wU9z0W1IdJc600SOi9axSyx75sOreqQGj8IS5iYZxX4dkb6b9z1vKdY04NE5YtzY8zcr1eoYU="
    - secure: "avJlfPkRYnJsSZ+7dq1QyX2ECP+AtNMjzSzW3LE/JCpi6gxzHiZBGssRghhHdZUS8eDjC8duRvefVtlq5BS/uK8dKNPEAABg/tMrIKII3yg2xfTZ2Yof2gdJcAhBhE9po1l8yILlAnlUGeFPPT29WhwoZ1VeMYHYwjwhkQiXUzY="
    - secure: "NFwn9ew5Fh6tr5rCh/Ll9MMnHfG6pFTYOl5siT6iVZxcoYg2HL/ao8NIje7nwdUBoLRQl/B1R53nuzq/Ru/hQda+1GXftmsr0+ofB7+Td2WFrAjWEqPvxzNjmBWhecU64dPjKRHcbSpr6zc6gJsp2PrbatZFN8nsY8uIoTeNCio="
    - secure: "ANlVtuITRGJTZQJINhOLc9rCkGpHRYWHW8ojd8USbm4twOe1AfPNhRbZo7UVSmY0OifFWY0e/1VCbJ5hy5Ng6GOiUXYXWu90IZb0TLvlsbevfyJymbnTVoNF2gwLLWXDkBShsKmGR7wFUh76wPzTBCYNq4/Os3Fpfvew4fMg3JQ="
    - secure: "A2/zf0C+KCoXXjmwtM8i0fiEtkkzogMDG3eeGpq7KmV7GZYxpNB2Dz3+gsEVTq5ZvLIVglckZUjNojh0QInnH1SMsheT7CQmp9upsr8g5INneBsDbqrnJSs3VC/iVJDjfWu1DtTviHjcdklzd3w0qWt3iXFcfHSCWJugdm0JjEI="
    - secure: "TJagzybkCyWoiNAMHkE8yyjmpnkjFMwcyv/BqI2jCqMvQaU56M8athMZ1x4fy9tHkV0vcYshRIPCLXcVhOPnneil+PvlQ6w6uOdZ/39mumRHPIpTCLA+sqE46hleSP2qQVb3fkkRgKW9IRsvHA6JtMSdRzaZ5y3V9r1Bz1j6hLM="
    - secure: "NchhVzKBPMjE59O9+iuXDl/G+O5SBFt+eZYzSTstbKgcvGOBn8TORGUm5+AVzRPLnw0QaZKu+MzePD0YnYaf/sCbp6g52G3aTr12htj3RoaLJ7dLySAEgkkdryENWyY3ssiamnF29RW5AWu/2oSdU/u9/+NPYPnrs+I0puifFtg="
    - secure: "NZs4x8Ezo6C6kra5LN9sPVHxA0D2V+N2WA1SRA47JziEI3YBfD4q0FJAgh5fbRqXl6AkGutgZF456RJw930xRUzhrTu0Pagm9cFqoTQCwVPMfIF9+73X+g3v4q5yTXq4ecD5k9ii6PNsPllE79dlyG1WmARtwNnXwnWHsfdxqp0="
    - secure: "CPk3YanB+EAfFh/m8n41ozxi9QzzIBlQ02ewV/Oc4cUv/63eZKaTEeRLgt6BH5UWJrRayNEyPU4gQliaRRAI1z7mhmVbXZlR5x+usvBdbQGcy0gLdY+tF2nx9dWqcgIhMQxnRDqlJH4dMiD40+2AzHyYoQWIEVzO8gvG6mcd35k="
    - secure: "Y5HVPyuxf/CfKAxeUW7sCSxOA+5MsizluK/bvhx0EiUZ5gKETdnRgev8t0BttNrAbsyzDZxCyXjhCsP1AJoTkSa6abGz1fIlAlwwc22gjMrRiafOLraBUz8Te1oKRBw/T5JdRqI87cWDS7mpIzl/I/9xN7uHbyl2TVNFvQ+b6yw="
    - secure: "dZ6SgH4+uAYGjAXtqqdyb5kgIo5b/bJyGYl6dSrY4nFPMKPpDhTAf0nDaG5taLZvq6BmqISuGK0p+rrviKg2bZ1expTr9Y1itDFiMhYLLSGtVooa4M8zwHQ0r86PcqUAa4Nkjmo19A3oTgXF6LAtsSp4NbNL2haAJW8vn7tObIg="
    - secure: "fPjI9pZXCABOjrbAps148F29VLlJwl/byl0tCvsK5WuDLhelxcj3urnAljmqQfhYRfSJ8MxFMTz6heKhZJBgZmi5C4PSos2J8Sr5guZNrFpK+tKinloJqke+/RXe8OC2FGIBiYrfRaAZnCQuyGGMggL/FkNB8cwj+4SCSO7yu6k="
    - secure: "IQjApRWcuk0vMAJDRDr7lsKg/taJ0qCIggVTy2x354vQKaeeUaDS+GzmNZbxeQzR1zWcHDGV2p0EKSZlbfa/psRWO5GYUWpXkfnjxuOSmZGLDrQhk5yVEZAAFjw0HreWYdqGoU85d1DFYt87w5282t78k3xDbYlWTvLZyvUiogY="
    - secure: "Fvwak487z4R6tdfUDQ7+z4qVuXUMjg8h23i87BvbyRviCDSIABNI+kgQLgTKaFbYFRtSKbc99Sn3RAdpfv39LAd7UhT6XuHWueK27Wcgozo0HWOqJJW06MCeRo4hSDJYqrDjWetbGkhDRQGSVti+FHjERw7rqIBeuaiFvf3eq0w="
    - secure: "VVlW1DXmLdUByzKg1SrVPw3aSaaecsRbSfZAzNCKlGkCmiT3WFqv8COx4hof7yXfbP35EEWmiijXl+9Au6HagTchH6E2fYwsHfq42sdsTQOiDm3ks2TpGoHBOIaftANTB9aW9LyMoAe5D7Cw+7A9ehc2PsvyTqCOP18tiFo+eeE="
    - secure: "AaahmxnDej3s9R5tIGFofu2ASDt9WNKRdE+zfwyW25rbaKmXcw8l1PW9bgGWkHZ2kZBjee3RC/Up5WY1as4Iz0GATroMfu/N7qJCO1PgVa0oZKCTk3HGqsEtLmFUm7LM5T1KMg5NCoyq5poXXHNpF5Z3l6rP36QEHMJRYf9vZjg="
    - secure: "C1gN3H4wsOeUj55esYTEwDCvv1soKg7trjrMcQhEFSF0n/EEpCJuM5k7cbVNfxmd8oBhu5fQQzn4K+N2Xj45NheXqAnZNZpUSuP7xPhq21X1pe7kSj4/4zCUKRIGJLy381uDj1G9aKDz0j219IcKcqHJN7npqapg3XC9TmQo82Y="
    - secure: "DTDEcO/o+Tw4KcWJ2757HRx/Fb1ngeLyzeejcDjnbc/tblreW7Vgs3RN8S4hGG4lioq9tXnX3e7xokxUoIS/X8EJukg6z0vxLmlpBg0VA8hUJ3Z10N6NJQL0dzsyWq0FYxFGTTz3Ix5RVUR7J7YjlsQWSsHTZXhD5x6P1VU9VTY="
    - secure: "OYgZdjl4WBn4hUelpLLTV5+RHmtx/Bk7Cn0D/OOlFeF1EV0ASgo5n7/OR0y1UNgpKrnaLjsC88uGxg9r+otsHRKwfKYcJ3pX3hKW0H1ETajaBjNUH5ofVkXYAdeI/LkM6XbZUQx9QAwdUDBauBia0Ob07lhzxwk+XjvBKoR7lw8="
    - secure: "NKxkYUu4DeZAkLnToh/fWYDLBzJWqyH+pvKFNTnN4OZhApWwyYW2fcnBFyBwzTQabjvjsPLM8f85flaejIX5K0nz5p/rZsFBcZa3QCVvc1CikkXz8U7Hn1O00V5d/6yXsGNhSxDBTTbtsmMrGSE/f89InRP5QCd6g4UUa/9waLM="
