language: java
jdk:
  - oraclejdk8

install:
  - sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
  - sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - sudo apt-get install python-pip lxc-docker
  - sudo pip install ansible

before_script:
  # Unpack ssh key for GCE
  - echo "decrypt private key"
  - for i in {0..30}; do eval $(printf "echo \$id_rsa_%02d\n" $i) >> ~/.ssh/id_rsa_base64; done
  - base64 --decode ~/.ssh/id_rsa_base64 > ~/.ssh/google_compute_engine
  - chmod 600 ~/.ssh/google_compute_engine
  - ls -la ~/.ssh
  - ssh -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o  StrictHostKeyChecking=no -i ~/.ssh/google_compute_engine -o LogLevel=QUIET -A  -p 22 vagrant@146.148.3.93

after_success:
  - ./gradlew :boos:bintrayUpload -PbintrayKey=$BINTRAY_KEY -Pversion="1.0.$TRAVIS_BUILD_NUMBER" -x publishMavenJavaPublicationToMavenLocal
  - ansible-playbook  -i env/deployment/lc.ini env/deployment/0_prepare.yml --extra-vars '{"application_version":"1.0.'$TRAVIS_BUILD_NUMBER'","project_root":"/home/travis/build/webdizz/bootiful-apps"}'

env:
  global:
    # ENV variable with Bintray API Key
    - secure: "PnbLPd2lg3eLqpBzZOT1LZYeszPIm0wcCd6pVb/tp/E1wI9vD544CCtmMo1pfE+gnybqb4mNzC+1VUFhUOTdUtqiuPO+4lebg+x/Bc8aPc8J/B7Gx5+qK/HCJrKzj9NjtArAGeXh65z4Miyg1p+OuXD9Zi/MvBi6ExGCz6c9cFA="
    # ENV variables of encrypted Private Key for GCE
    - secure: "T3XMRouK6W4wazx9EfRDDSO5benU5pXefI44H4kfo6IIc6VqtpOrBaYVkPE+bgsRArOx0SpS/Z/wVXMnPIQgAkXVmScIFfOeeImwtkttJXSlFHXMoL53kAd61CxZAlKYoGreUhR1HLt4MGgQLftAhVNwGL7EnxTaJifKCYdMlfA="
    - secure: "GIEZyJtT1YG0RIi5ochnAedKFYJuCizdukq1HHB2eTWCoBUmEBPyoVbeUNXlG5Yy8kNHSQFVGaALh7mepGlmbPGq1F0Fhwa74QPsp0e11BQz/eMrHCuvmpa3UsX78xxSMr/MRRn3epQ2R/AVj1mzWF7Reiw6kYDqi/G7NCLEIRA="
    - secure: "WN0kXYf4qhC9lHHclWu76C0eKUOlcXP6kjhqHFPoksWX1IDcqVzP7fJCAqB7DiKDqHxaGqwKuPFzNTnbmSJrxlk5isvaBVMps8G5yHgY1XqTIpv8ergZzezmc0JR5k58zYOc3Zt2nJ9R3gcdK0Uiqwb66sZ5uuJGi/VTtgWZkNM="
    - secure: "XzXa40WiqeSkzMeyJ8upPlXlxGA2EU1O3gxrR54JCr0uwZt5EjBMP+YU7AXWyruznsXewnK0NzHYo6d//mOwJrZrsMY23JzmRuIw45Ob3rkkPvDKcNwsPA5DsEdqQzfwy2HiW7u9exSMriP1ujwC/kmHELHVO5IVpQ85sx4OdXU="
    - secure: "E3XnK5QIohG3EA/ES8bq8tX/bYWRnSk1HlllbXES7R4ZK+MaA1jGS9ielBMNU6jlIRMz4t+rmI87ASf9nKiw1uKxaQidLnxvPqc/lB1a6kQr6vP3abfAcKkXH60G3BKS2WTzWfQifDjVkcvBj/7PijWhAWqiio4/WsasXy6nO2E="
    - secure: "Z7aFumVSqdeUNRim7SXjvPNj8oRzlP71Li8iMhCA6kjt70Z+59m8ucOhYTwtcuWG/e6LbSAMthFbYw3la9UREloeh8zaHRatu0aW1Pobj+/CiiheK3qKqCifDtqtAXepIygZxUdHuQkxP5AcHxG5jH3RjDoNuPe1uJ60gkEu8e8="
    - secure: "GQbQF/fIwoPQJRmvApVSSPKo/E3GPmrjB/CpQuOtsKHXXodQxnChxloU44/+ZWJbYOsAMwHAW+YScX4yM8Gug/H9CgPYSzANjcNXEG4+cSDIVN37+y3FVYtqGQKS3Hs06QopXQVfbEPWFxchVoyzJPhxDyFS/XZ+jNJM0UhvU/I="
    - secure: "LnHpMD12zf2OoeFrsyHOBqw8ki3L0DL1E6BQwWGwVA0e/WFL1nss3HBYGzo7xXwq0PsaGR+0eCzYgHar4zMYfOcujjQUeZ7DKoDabUfMIQPBzdF7CBQZXkpnsmDvRgi2LEEBuL+St4fOxVs5KmJinaDDRaMs/0LzKnoybWgbdSQ="
    - secure: "Pzu+2e1lmgF2WOdW61M74XM7H8GNvERH6t19wFfzCFSex5hNPEiDyK7/c25M6iZM5VZ9a3K8PPAUgMmtryWD72mtIh39ExWqT15hktmfAspYqqp+tdqK4l0nIDok7ZiDJAp8e5ON2AxLstrgQu3ysvBSTc8zktjJXjeaClKHqR0="
    - secure: "dmJWwj0kbq4+1832ehhXWeCg2TlWzyGYvmRfPsXHLyKcnzNtLA5sBlSW/g9umaNe5/I1Cut4JsaiOwK5kEUXXRTJnzKJrjAgEd1zs3bHNkaHo7MZSYfMyB5Zr0xVjmWjo6jYbC51x1WQHkilskr8aBf0al4/nTSOL+vE+Dj41cI="
    - secure: "W49j32npxSBM6lb9gjyMVrrMpsNpl5u/0C7Nh4H/gFgPmLgCfUFQbgeOnCwoBpylqXC+Ppd80IsQDbUAwsWLEsAJMHkc7iy7rypkeerijvDG/o+61nUjt2qhEHPqQNQLAzivWl5/ARGsydcgQ/Yf4mEpBXPUmd6jmXT7UwfsoVw="
    - secure: "NwTBF3k1Fm7xb5pv47gqr9K5z8Yd9kffp1FxXD6it1tZvaRRtn+VG9WPaNmuXIXnJfp85F3KZZERAYTkFFhBNkdK9o3dRnLh3FzhOd55iuvIKu7jvmrm1N4d5Jwpz7xfp3q9fpP8Ft7O44iLrrRiB6WZ96KM0vvfRZefFLMGwI0="
    - secure: "LNO7GL4gafNqtIBA8ei04BCvWrlaiD7k/3Oqsy5s3JCiuG2kJnbN2ywQANC7BRtctFRFUbNwcd4QPA85aHfQ/eJtUFl/l+RxDr51+Y+TFDI3yqG0LS9BicTG5Iqcbh7x6fBv49VTqyuua8UkrCZQ1uOKa9MjNN2gicA1w6PfC2c="
    - secure: "HkWGjUfISWt0SPK0IrzEJBuEgpd+lS1J/zjROrZ8jlsjOiHzk4cTFlaAPoic0wy/vZHSAb40/26qq0rUi/en+0JMCRji+5PceDLyufixt90K3y8JrB26J2OTUVUZzY+VMHYo2seWUGDITHROw5/KZWESNkLPqYw278XIZoAWGYk="
    - secure: "Ym3kjcBmYlU75IuZP/QsYsRxZZUR8CohOyL9u4QBLmC60szeISBzvfkKTZ/S/BQ4gmWO3PSkNWU8fmfh57kgMHKsxHQfzG/+n7G/MucxDBHMLhl5gKKdGZCsGDNP/Eo0QXYdhwIBeYFS2+b5zL5fjxIQjwSgXoyDkuaYG91Z+7M="
    - secure: "ZRs1dOWoW1tvg3U2RwzdHvMStqqusXPwJnYdniOSxw3k8TjPlk4xgiYRyqmK7EKW0pcUPrUcwTl4VSiubvDaVkLqtEgDbVbgRXQhut0s1XI/LX/t9opj1tJQSDbYiskPcOATJ24EDvwlgIq79IehqbREbfxyg/VdBfwwEaPUKnE="
    - secure: "FszaXFcWZtZ3SV8C5OjMNBdxS+thmvGOO80COt6U+pqwCAcBgKEP4gwTfR6MlpBxAOibIINnrUrurAwLi6VUckRKWTqdmyK13UbVkxAQz/G+j6fWU9JvkWC9jEUPfUL7gndCtIZjFK17dll96DT8sw1VXTNio+zvcHKeZG/Xiog="
    - secure: "J+rA5iwbnakIxAYlaLJ/KxOzlHEkrUKfVJ3ru1SkZLPykWO5Ny2xrLCzkz2ybS/Bzh/GVciMBiJ3vTXuDyZwJapgWd/BI5cInA+JC9Cz4VNTzWG8m12or4yRl+FIZq4WTAKhxyHIWcGyXUp1BkiqiagCI9BoxipsQt5/sLMG/s4="
    - secure: "de/A/YzW4QEQdxFeBY9dYUBUVP92WTQ5B8rRD5XD1DAYZ9ec+ZC5VJt3Q7XbDQ6zn9SrlpKa0I6chjx3QAZvoTxVFBHjHHA3ocntae5Cjb09y/izA74aYtyC2C08V06RIURoHvFbDBo2xNOxYrpsLPwyq0EqsiSg/ORFUJn9X8o="
    - secure: "DIpsQHf4TToQXo4fouS0O58vDrUa/Mpnvlgz1xRWyhKtZcW5r1/hwpt3OoJFgC7Vgw8JNIISa3hvaDp0un93wcfZk4N8/iSx/GbmVjF4HmxU52mzB6uRzyk78J7Zi6scRUnDYT11dhhc8Ir5cb5bCqqd3ZQPabtdtRpAG7l2SEA="
    - secure: "CKZenyy4onDkFqgGu/cuOu635Ib7Xk7Gxi7hGZd+7/ZqB5lYRsrkIGBjbrwdQAT0cKAaXq2MEdqPhGzS0kiow8sFHlgVT6c8EK9X91q4d3RzfeZysz16qoRW2k2aH7UQvxq6BwinDk0bxZKnvNzL2dOw3m+yZsmIotR+0TzI4+g="
    - secure: "cIb6IXYK0Q/5yfGOLN9STITDrYC2vMtxs3sZpzWUdSnhSiSP6lWl9x3pRw59A+n9ufXoSCwi0DId717bL6aUi9MeSg7PZuUqLHwiPgGJW5Aycb5ox2Yec02qyTI+IOZszHrAul9a7QGU1y9kgA3CpyuM6GPsWz3MZ0xdBCQjpX0="
    - secure: "Nfpo3IvVGwxcl1UHY3uqpE1YFzO/vIFguOE5EZO/tMUcGtKASQT8K9imornwA7Y9Kez5dn5E4MpXARVFYI7DY2k/jOxdg57FBZfawBk3+GZonDfewXdaz1R19zn8S/9E5oWLFzcdbRoVwkgNNquo3hCoipS9ojTE4d51cNP+OEk="