server:
  port: 8070

spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.71
  social:
    twitter:
      appId: YdOWtGtbEBHMXjZPzboi8F0Ec

---

# configuration for local cluster
server:
  port: 8080
spring:
  thymeleaf:
    cache: true
  profiles:
    - lc
  redis:
    host: redis_1

---

# configuration for GCE cluster
server:
  port: 8080
spring:
  thymeleaf:
    cache: true
  profiles:
    - gce
  redis:
    host: redis_1