spring:
  social:
    twitter:
      appId: FUdxv0M8fVNnuSOIZi3wwoJdg
      appSecret: use_env
      accessToken: use_env
      accessTokenSecret: use_env

---

server:
  port: 8070
spring:
  profiles: ld
  redis:
    host: 192.168.56.71

---

# configuration for local cluster
server:
  port: 8080
spring:
  thymeleaf:
    cache: true
  profiles: lc
  redis:
    host: redis_1

---

# configuration for GCE cluster
server:
  port: 8080
spring:
  thymeleaf:
    cache: true
  profiles:
    - gce
  redis:
    host: redis_1