@startuml

actor User

package "Boosenger" {
    [MVC]
    [MessageRepository]
    [Social]
    [Messaging]
}

package "Twitter" {
    [REST API]
}

database messages

User -right-> [MVC]
[MVC] ..> [Messaging]
[MessageRepository] -> messages
[Messaging] -left-> [MessageRepository]

[Messaging] -> [Social]

[Social] ..> [REST API]

@enduml