---

  - name: Install required system packages.
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: system_packages

  - name: Install required Python packages.
    easy_install: name={{ item }}
    with_items: python_packages
